autonomous easy config: true
default weather: clear
default acquisition parameters:
  clear:
    FPS: 10
    IntegrationTimeRGB: 1000
    IntegrationTime800: 2000
    IntegrationTime975: 5000
  partly cloudy:
    FPS: 10
    IntegrationTimeRGB: 1000
    IntegrationTime800: 2000
    IntegrationTime975: 5000
  cloudy:
    FPS: 10
    IntegrationTimeRGB: 1000
    IntegrationTime800: 2000
    IntegrationTime975: 5000
  output types: ["equalize hist", "RGB", "zed"]
custom acquisition parameters:
  FPS: 10
  IntegrationTimeRGB: 1000
  IntegrationTime800: 2000
  IntegrationTime975: 5000
  output types: ["equalize hist", "RGB", "zed"]
batch size: 4
max batches: 30