citrus:
  autonomous_easy_config: true
  default_weather: clear
  default_acquisition_parameters:
    clear:
      FPS: 10
      IntegrationTimeRGB: 1000
      IntegrationTime800: 2000
      IntegrationTime975: 5000
    partly_cloudy:
      FPS: 10
      IntegrationTimeRGB: 1000
      IntegrationTime800: 2000
      IntegrationTime975: 5000
    cloudy:
      FPS: 10
      IntegrationTimeRGB: 1000
      IntegrationTime800: 2000
      IntegrationTime975: 5000
    output_types: ["equalize_hist", "RGB", "zed_gray", "zed_depth", "svo"]
  custom_acquisition_parameters:
    FPS: 10
    IntegrationTimeRGB: 1000
    IntegrationTime800: 2000
    IntegrationTime975: 5000
    output_types: ["equalize_hist", "RGB", "zed_gray", "zed_depth", "svo"]
  batch_size: 4
  max_batches: 30

apple:
  autonomous_easy_config: true
  default_weather: clear
  default_acquisition_parameters:
    clear:
      FPS: 10
      IntegrationTimeRGB: 1000
      IntegrationTime800: 2000
      IntegrationTime975: 5000
    partly_cloudy:
      FPS: 10
      IntegrationTimeRGB: 1000
      IntegrationTime800: 2000
      IntegrationTime975: 5000
    cloudy:
      FPS: 10
      IntegrationTimeRGB: 1000
      IntegrationTime800: 2000
      IntegrationTime975: 5000
    output_types: ["equalize_hist", "RGB", "zed_gray", "zed_depth"]
  custom_acquisition_parameters:
    FPS: 10
    IntegrationTimeRGB: 1000
    IntegrationTime800: 2000
    IntegrationTime975: 5000
    output_types: ["equalize_hist", "RGB", "zed_gray", "zed_depth"]
  batch_size: 4
  max_batches: 30