# config.yaml
exp_file: /home/mic-730ai/fruitspec/code/matan/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr_hires.py
#exp_file: /home/yotam/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr_hires.py  # counter
#exp_file: /home/yotam/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr.py       # baseline
#exp_file: /home/yotam/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr_syn_jai.py # pepper

#ckpt_file: /home/yotam/FruitSpec/Sandbox/Run_2_13_nov_2022/best_ckpt.pth # tomatoes
#ckpt_file: /home/yotam/FruitSpec/weights/fs_yolox_tiny_lr/best_ckpt.pth # pre-trained coco
#ckpt_file: /home/yotam/FruitSpec/weights/Run_2_7_oct/best_ckpt.pth # counter
#ckpt_file: /home/yotam/FruitSpec/weights/pepper/Run_3_22_oct_2022/best_ckpt.pth # pepper 200 img train
#ckpt_file: /home/yotam/FruitSpec/weights/pepper/Run_1_23_oct_2022_400img/best_ckpt.pth # pepper 400 img train
#ckpt_file: /home/yotam/FruitSpec/Sandbox/Run_26_oct_2022_curated_data/best_ckpt.pth  # new RGB tomatoes
#ckpt_file: /home/yotam/FruitSpec/weights/tomatoes/Run_28_oct_curated_2x/best_ckpt.pth # new RGB tomatoes 28/11
#ckpt_file: /home/yotam/FruitSpec/Sandbox/Syngenta/weights/tomatoes/Run_30_oct_2022_1Class_aug_tasq/best_ckpt.pth # new RGB tomatoes 1 class 29/11
#ckpt_file: /home/mic-730ai/Documents/Expriments/weights/Run_2_7_oct/best_ckpt.pth # RGB tasq v2
ckpt_file: /home/mic-730ai/Documents/Expriments/weights/Run_2_7_oct/fs_yolox_tiny_lr_hires/model_trt.pth



device: cuda

input_size: [1024, 1024]
batch_size: 4

detector:
  confidence: 0.4
  nms: 0.65
  num_of_classes: 1
  fp16: true
  fuse: false
  trt: true

classes:
  full: 0
  partial: 1

tracker:
  minimal_max_distance: 10
  major: 4 #3
  minor: 0.5 #2.5
  max_losses: 5  # 10
  score_weights: [0.25, 1.0, 0.25, 0.0]  # [0.25, 1.0, 0.25, 1]
  match_type:  inter #center #
  det_area: 0.7
  translation_size: 640
  compile_data_path: /home/mic-730ai/fruitspec/code/matan/tracker_init.pkl
  debug: false


translation:
  translation_size: 480
  mode: match # match: use template matching, keypoints: use keypoints detection
  dets_only: true # true: perfrom on detections only, false: on entire image


sensor_aligner:
  zed_roi_params: {y_s: 250, y_e: 1650, x_s: 0, x_e: 1080} # jai search region in zed
  size: 640 #what size to resize image to
  affine_method: keypoints # keypoints will use keypoints, loftr will use loftr
  ransac: 20
  sx: 0.60546875
  sy:  0.6133919843597263
  roix: 970 #930 #937
  roiy: 1255
  debug:
    preprocess: false
    keypoints: false
    kde: false
    homography: false

frame_loader:
  mode: sync_mkv # sync_mkv, async,  sync_svo


filters:
  distance:
    threshold: 1
  duplicates:
    iou_threshold: 0.6
  size:
    size_threshold: 2500
  height:
    bias: -100
    y_crop: 200
  hue: true # flag for using hue filter
  depth: true # flag for using dynamic depth filter

clusters:
  min_single_fruit_distance: 150

