# config.yaml
exp_file: /home/fruitspec-lab/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr.py

ckpt_file: /home/fruitspec-lab/FruitSpec/weights/fs_yolox_tiny_lr/best_ckpt.pth

device: cuda

input_size: [414, 414]

detector:
  confidence: 0.8
  nms: 0.65
  num_of_classes: 3
  fp16: true
  fuse: false
  trt: false

tracker:
  track_thresh: 0.6
  track_buffer: 30
  match_threshold: 0.9
  min-box-area: 100
  mot20: false

