# config.yaml
exp_file: C:\Users\Matan\Documents\Projects\fsCounter\vision\Detector\YOLOX\exps\default\yolox_tiny.py
ckpt_file: C:\Users\Matan\Documents\Projects\weights\yolox_tiny.pth

device: cpu

input_size: [414, 414]

detector:
  confidence: 0.8
  nms: 0.65
  num_of_classes: 3
  fp16: true
  fuse: false
  trt: false

tracker:
  track_thresh: 0.6
  track_buffer: 30
  match_threshold: 0.9
  min-box-area: 100
  mot20: false

