# config.yaml
#exp_file: /home/fruitspec-lab/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr.py
exp_file: /home/yotam/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr.py

#ckpt_file: /home/fruitspec-lab/FruitSpec/weights/fs_yolox_tiny_lr/best_ckpt.pth
ckpt_file: /home/yotam/FruitSpec/weights/fs_yolox_tiny_lr/best_ckpt.pth

device: cuda

input_size: [414, 414]

detector:
  confidence: 0.1
  nms: 0.65
  num_of_classes: 3
  fp16: true
  fuse: false
  trt: false

tracker:
  frame_rate: 30
  track_thresh: 0.2
  track_buffer: 30
  match_threshold: 0.9
  min_box_area: 100
  orig_width: 2048
  orig_height: 1536
  mot20: false

