upload_bucket_name: fsCounter
upload_prefix: uploads
counter_number: 1
logs_path: "~/Desktop/counter_logs/"
log_name: "log"
GUI: false
autonomous_acquisition: true
customer_code: "NWFMXX"
use_strace: true
