counter_number: 4
GUI: true
autonomous_acquisition: false
customer_code: "MOTCHA"
crop: citrus
collect_data: true
debug:
  # if 'is_active' is set to 'False' then all other values are automatically set to 'False' as well.
  is_active: true
  crash_syslog: false
  mtu_log: false
  jtop_log: false
  constant_jaized: true
