upload_bucket_name: fsCounter
upload_prefix: uploads
counter_number: 1
logs_path: "~/Desktop/counter_logs/"
log_name: "log"
GUI: false
autonomous_acquisition: true
customer_code: "MOTCHA"
led_exe_path: /home/mic-730ai/fruitspec/fsCounter/application/utils/diotest