upload_bucket_name: fsCounter
upload_prefix: uploads
counter_number: 4
logs_path: "~/Desktop/counter_logs/"
log_name: "log"
GUI: true
autonomous_acquisition: true
customer_code: "MOTCHA"
use_strace: true
