kml_bucket_name: "fruitspec-intgr-caliper"
s3_kml_file_name: "Blocks.kml"
GPS_device_name: "/dev/ttyUSB1"
kml_path: "/home/mic-730ai/Desktop/Blocks.kml"
led_exe_path: "/home/mic-730ai/fruitspec/fsCounter/application/utils/diotest"
led_blink_sleep_time: 0.2
no_gps_in_plot_limit: 300
sample_count_threshold: 20
minimal_time_in_state: 3