kml_bucket_name: "fruitspec-prod-caliper"
s3_kml_file_name: "Blocks.kml"
GPS_device_name: "/dev/ttyUSB1"
kml_path: "/home/mic-730ai/Desktop/Blocks.kml"
led_exe_path: "/home/mic-730ai/fruitspec/fsCounter/application/utils/diotest"
led_blink_sleep_time: 0.2
