output_folder: /home/matans/Documents/fruitspec/sandbox/Apples_Golan_heights/OLD00000/230523/row_1/1
sync_data_log_path: /home/matans/Documents/fruitspec/sandbox/Apples_Golan_heights/OLD00000/230523/row_1/1/jaized_timestamps.log
slice_data_path: /home/matans/Documents/fruitspec/sandbox/grape-scanning_2023-05-18_0720/row_4ZED_1_slice_data.json #/media/matan/cam172/customers/DEWAGD/240123/DWDBNB05/R5A/ZED_1_slice_data.json
frame_drop_path: /home/matans/Documents/fruitspec/sandbox/grape-scanning_2023-05-18_0720/row_4/frame_drop_1.log
debug_folder: $(output_folder)/debug
rotate: false
zed_shift: 0 # default 0
max_z: 8
overwrite:
  adt: true
  trees: false
create_full_features: true
last_slice: false
model_config: /home/fruitspec-lab/FruitSpec/Code/roi/fsCounter/MHS/model_config.yaml

zed:
  movie_path: /home/matans/Documents/fruitspec/sandbox/Apples_Golan_heights/OLD00000/230523/row_1/1/ZED.mkv
  frame_size: [1920, 1080]
  rotate: 2 #0: no rotate, 1: rotate countercloclwise, 2: rotate clockwise
  depth_minimum: 1 # 1 counter
  depth_maximum: 8 # 8 counter
  #channels: 1
  channels: 3

depth:
  movie_path: /home/matans/Documents/fruitspec/sandbox/Apples_Golan_heights/OLD00000/230523/row_1/1/DEPTH.mkv
  frame_size: [1920, 1080]
  rotate: 2
  channels: 1

jai:
  movie_path: /home/matans/Documents/fruitspec/sandbox/Apples_Golan_heights/OLD00000/230523/row_1/1/Result_FSI.mkv
  frame_size: [2048, 1536]
  rotate: 1 #0: no rotate, 1: rotate countercloclwise, 2: rotate clockwise
  channels: 3

rgb_jai:
  movie_path: /home/matans/Documents/fruitspec/sandbox/Apples_Golan_heights/OLD00000/230523/row_1/1/Result_RGB.mkv
  frame_size: [2048, 1536]
  rotate: 1 #0: no rotate, 1: rotate countercloclwise, 2: rotate clockwise
  channels: 3

frame_size: [2048, 1536]

debug:
  tracker_windows: true
  tracker_results: false
  det_results: false
  raw_frame: false
  depth: false
  tracker: None
  trees: false
  features: false
  align_graph: true
  clusters: false
  run_type: RGB_siftv1_kp_equalize # align graph naming




adt_debugger:
  scan_type: "multi_scans"
  row_path: /home/matans/Documents/fruitspec/sandbox/Apples_Golan_heights/OLD00000/230523/row_1/1 # path to row for analyzing, this should be a path to the fodler contatning all the files if we have multi scans
  block_path: "" # path to block for analyzing, if "" will run only on row
  include_rows: ["all"] # which rows to analyze if it includes "all" will run on all
  include_scans: ["all"] # which scans indexes to analyze if it includes "all" will run on all
  rotate: true # flag for rotating video
  frames_limit: [100, 400] # frames to analyze in video
  fps: 10 # fps for writing the movie if 0 will use original fps
  new_vid_name: "" # name for new video: "" is for default value (Result_FSI_{side}_with_dets.mkv)
  outputs_dir: /home/matans/Documents/fruitspec/sandbox/debugging/ # where to dump the images
  block_suffix: 1 # suffix for output dir naming
  t_index: 6 # index of tracker
  methods: [jai_frame_w_dets, alignment] # which methods to use: ("vid_with_dets", "jai_frame_w_dets", "alignment", "trees")
  alignment_methods: ["min_samp_depth"] # which alignment filtering styles to use ("", "depth", "min_samp", "min_samp_depth")
  max_depth: 5 # maxium depth allowed for a detection
  im_output_shape: [600,900] # what output shape to use
  min_samples: 3 # min number of samples for a track to count as valid (>=)
  filter_depth: true # flag for using depth filtering