output_folder: /home/matans/Documents/fruitspec/sandbox/VALENCIA/row_1A/adt
sync_data_log_path: /home/matans/Documents/fruitspec/sandbox/VALENCIA/row_1A/jaized_timestamps_1.log
slice_data_path: /home/matans/Documents/fruitspec/sandbox/VALENCIA/row_1A/ZED_1_slice_data.json #/media/matan/cam172/customers/DEWAGD/240123/DWDBNB05/R5A/ZED_1_slice_data.json
frame_drop_path: /home/matans/Documents/fruitspec/sandbox/VALENCIA/row_1A/frame_drop_1.log
debug_folder: $(output_folder)/debug
rotate: false
zed_shift: 0 # default 0
max_z: 8
overwrite:
  adt: true
  trees: false
create_full_features: true

zed:
  movie_path: /home/matans/Documents/fruitspec/sandbox/VALENCIA/row_1A/ZED_1.mkv
  frame_size: [1920, 1080]
  rotate: 2 #0: no rotate, 1: rotate countercloclwise, 2: rotate clockwise
  depth_minimum: 1 # 1 counter
  depth_maximum: 8 # 8 counter
  channels: 1

depth:
  movie_path: /home/matans/Documents/fruitspec/sandbox/VALENCIA/row_1A/DEPTH_1.mkv
  frame_size: [1920, 1080]
  rotate: 2
  channels: 1

jai:
  movie_path: /home/matans/Documents/fruitspec/sandbox/VALENCIA/row_1A/Result_FSI_1.mkv
  frame_size: [2048, 1536]
  rotate: 1 #0: no rotate, 1: rotate countercloclwise, 2: rotate clockwise
  channels: 3

rgb_jai:
  movie_path: /home/matans/Documents/fruitspec/sandbox/VALENCIA/row_1A/RGB_1.mkv
  frame_size: [2048, 1536]
  rotate: 1 #0: no rotate, 1: rotate countercloclwise, 2: rotate clockwise
  channels: 3

frame_size: [2048, 1536]

debug:
  tracker_windows: false
  tracker_results: false
  det_results: false
  raw_frame: false
  depth: false
  tracker: None
  trees: false
  features: false
  align_graph: true
  run_type: RGB_siftv1_kp_equalize # align graph naming




