output_folder: /media/fruitspec-lab/cam175/customers_new/DEWAGD/DWDBLE43/190123/row_26/2
sync_data_log_path: /media/fruitspec-lab/cam175/customers_new/DEWAGD/DWDBLE43/190123/row_26/2/jai_zed.json
slice_data_path: /media/fruitspec-lab/cam175/customers_new/DEWAGD/DWDBLE43/190123/row_26/2/slices.csv
frame_drop_path: /media/fruitspec-lab/cam175/customers_new/DEWAGD/DWDBLE43/190123/row_26/2/frame_drop.log
debug_folder: /media/fruitspec-lab/easystore/testing_playground
rotate: false
zed_shift: 0 # default 0
max_z: 5
overwrite:
  adt: false
  trees: false
create_full_features: true
last_slice: true
model_config: /home/fruitspec-lab/FruitSpec/Code/roi/fsCounter/MHS/model_config.yaml

zed:
  movie_path: /media/fruitspec-lab/cam175/customers_new/DEWAGD/DWDBLE43/190123/row_26/2/ZED.svo
  frame_size: [1920, 1080]
  rotate: 2 #0: no rotate, 1: rotate countercloclwise, 2: rotate clockwise
  depth_minimum: 0.5 # 1 counter
  depth_maximum: 20 # 8 counter
  channels: 3

depth:
  movie_path: /media/fruitspec-lab/cam175/customers_new/DEWAGD/DWDBLE43/190123/row_26/2/DEPTH.mkv
  frame_size: [1920, 1080]
  rotate: 2
  channels: 1

jai:
  movie_path: /media/fruitspec-lab/cam175/customers_new/DEWAGD/DWDBLE43/190123/row_26/2/Result_FSI.mkv
  frame_size: [2048, 1536]
  rotate: 1 #0: no rotate, 1: rotate countercloclwise, 2: rotate clockwise
  channels: 3

rgb_jai:
  movie_path: /media/fruitspec-lab/cam175/customers_new/DEWAGD/DWDBLE43/190123/row_26/2/Result_RGB.mkv
  frame_size: [2048, 1536]
  rotate: 1 #0: no rotate, 1: rotate countercloclwise, 2: rotate clockwise
  channels: 3

frame_size: [2048, 1536]

debug:
  tracker_windows: false
  tracker_results: true
  det_results: true
  raw_frame: false
  depth: false
  clusters: false
  tracker: None
  trees: false
  features: false
  align_graph: false
  alignment: true
  run_type: RGB_siftv1_kp_equalize # align graph naming

adt_debugger:
  scan_type: "multi_scans"
  row_path: /home/matans/Documents/fruitspec/sandbox/VALENCIA/debugger_test/row_1/1 # path to row for analyzing, this should be a path to the fodler contatning all the files if we have multi scans
  block_path: "/media/fruitspec-lab/cam175/customers_new/MOTCHA/BEERAMU0/220823" # path to scan date for analyzing, if "" will run only on row
  include_rows: ["row_2"] # which rows to analyze if it includes "all" will run on all
  include_scans: ["all"] # which scans indexes to analyze if it includes "all" will run on all
  rotate: true # flag for rotating video
  frames_limit: [0, 5] # frames to analyze in video
  fps: 10 # fps for writing the movie if 0 will use original fps
  new_vid_name: "" # name for new video: "" is for default value (Result_FSI_{side}_with_dets.mkv)
  outputs_dir: /media/fruitspec-lab/easystore/debugging/ # where to dump the images
  block_suffix: _aligment # suffix for output dir naming
  t_index: 6 # index of tracker
  methods: [jai_frame_w_dets, alignment, trees] # which methods to use: ("vid_with_dets", "jai_frame_w_dets", "alignment", "trees")
  alignment_methods: ["", "depth", "min_samp_depth"] # which alignment filtering styles to use ("", "depth", "min_samp", "min_samp_depth")
  max_depth: [5] # maxium depth allowed for a detection
  im_output_shape: [600,900] # what output shape to use
  min_samples: [1,2,3] # min number of samples for a track to count as valid (>=)
  filter_depth: true # flag for using depth filtering