exp_file: /home/fruitspec-lab/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr_hires.py
#exp_file: /home/yotam/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr.py

ckpt_file: /home/fruitspec-lab/FruitSpec/Sandbox/Run_2_7_oct_2022/best_ckpt.pth
#ckpt_file: /home/yotam/FruitSpec/weights/fs_yolox_tiny_lr/best_ckpt.pth


device: cuda

input_size: [1024, 1024]

detector:
  confidence: 0.4
  nms: 0.65
  num_of_classes: 1
  fp16: true
  fuse: false
  trt: false

classes:
  full: 0
  partial: 1

tracker:
  minimal_max_distance: 10
  major: 1.5
  minor: 1
  max_losses: 5  
  score_weights: [0.25, 1.0, 0.25, 1]
  match_type:  inter #center #
  det_area: 0.7
  translation_size: 640


translation:
  translation_size: 480
  mode: match # match: use template matching, keypoints: use keypoints detection
  dets_only: true # true: perfrom on detections only, false: on entire image

filters:
  distance:
    threshold: 140
  duplicates:
    iou_threshold: 0.6
  size:
    size_threshold: 1000
  height:
    bias: -100
    y_crop: 200

clusters:
  min_single_fruit_distance: 150

