exp_file: /home/fruitspec-lab/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr_hires.py
#exp_file: /home/yotam/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr.py

#ckpt_file: /home/fruitspec-lab/FruitSpec/Sandbox/Run_2_7_oct_2022/best_ckpt.pth
ckpt_file: /home/fruitspec-lab/FruitSpec/weights/Apples_1_29_June_23/best_ckpt.pth
#ckpt_file: /home/yotam/FruitSpec/weights/fs_yolox_tiny_lr/best_ckpt.pth


device: cuda

input_size: [1024, 1024]
batch_size: 4

detector:
  confidence: 0.381
  nms: 0.65
  num_of_classes: 1
  fp16: true
  fuse: false
  trt: false

classes:
  full: 0
  partial: 1

tracker:
  minimal_max_distance: 10
  major: 1.5 #3
  minor: 0.75 #2.5
  max_losses: 5  # 10
  score_weights: [0.25, 1.0, 0.25, 0.0]  # [0.25, 1.0, 0.25, 1]
  match_type:  inter #center #
  det_area: 0.7
  translation_size: 640
  compile_data_path: /home/fruitspec-lab/FruitSpec/Sandbox/tracker_init.pkl
  debug: false


translation:
  translation_size: 480
  mode: match # match: use template matching, keypoints: use keypoints detection
  dets_only: false # true: perfrom on detections only, false: on entire image
  maxlen: 0 # max memory length, if 0 will not change negetive tx based on memory


sensor_aligner:
  zed_roi_params: {y_s: 355, y_e: 1635, x_s: 0, x_e: 1080} # jai search region in zed
  size: 480 #what size to resize image to
  affine_method: keypoints # keypoints will use keypoints, loftr will use loftr
  ransac: 20
  sx: 0.60546875 #0.6315104 #0.60546875
  sy: 0.6133919843597263 # 0.6133919843597263
  roix: 970 #970 #930 #937
  roiy: 1255
  debug:
    preprocess: false
    keypoints: false
    kde: false
    homography: false

frame_loader:
  mode: sync_svo # sync_mkv, async,  sync_svo

result_collector:
  mode: pc_dims # options "", depth, pc, pc_dims

filters:
  distance:
    threshold: 1
  duplicates:
    iou_threshold: 0.6
  size:
    size_threshold: 2500
  height:
    bias: -100
    y_crop: 200
  hue: true # flag for using hue filter
  depth: true # flag for using dynamic depth filter

clusters:
  min_single_fruit_distance: 150

