# config.yaml
#exp_file: /home/yotam/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr_RGB.py
#exp_file: /home/yotam/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr.py
exp_file: /home/yotam/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr_syn_jai.py

#ckpt_file: /home/yotam/FruitSpec/Sandbox/Run_2_13_nov_2022/best_ckpt.pth
#ckpt_file: /home/yotam/FruitSpec/weights/fs_yolox_tiny_lr/best_ckpt.pth
ckpt_file: /home/yotam/FruitSpec/weights/pepper/Run_3_22_oct_2022/best_ckpt.pth

device: cuda

input_size: [1024, 1024]

detector:
  confidence: 0.3
  nms: 0.65
  num_of_classes: 2
  fp16: true
  fuse: false
  trt: false

classes:
  full: 0
  partial: 1

tracker:
  minimal_max_distance: 10
  score_weights: [0.5, 1, 0.5]
  match_type: inter
  translation_size: 640

