# config.yaml
exp_file: /home/matans/Documents/fruitspec/Code/Matan/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr_hires_apple.py

ckpt_file: /home/matans/Documents/fruitspec/Weights/citrus/Apple_29_lune_23/best_ckpt.pth  #yolox

#ckpt_file: /home/matans/Documents/fruitspec/weights/v8/best.pt



device: cuda

input_size: [1024, 1024]
batch_size: 4

detector:
  detector_type: yolox # implemented: yolox, yolov8
  confidence: 0.3
  nms: 0.3
  num_of_classes: 1
  max_detections: 300
  fp16: true
  fuse: false
  trt: false

classes:
  full: 0
  partial: 1

tracker:
  minimal_max_distance: 10
  major: 1.5 #3
  minor: 1 #2.5
  ranges:
    close:
      dist: 1.2
      major: 1.5 #2
      minor: 0.8 #1.2
    far:
      dist: 3.2
      major: 1.2 # 1.1
      minor: 0.65 # 0.65
    mid:
      dist: 2 # not in use
      major: 1.5 #1.5
      minor: 0.8 #0.8
  max_losses: 3  # 10
  score_weights: [0.25, 1.0, 0.25, 0.75]  # [0.25, 1.0, 0.25, 1]
  match_type:  inter #center #
  det_area: 1
  translation_size: 640
  compile_data_path: /home/matans/Documents/fruitspec/Code/Matan/tracker_init.pkl
  debug: false


translation:
  translation_size: 480
  mode: match # match: use template matching, keypoints: use keypoints detection
  dets_only: false # true: perfrom on detections only, false: on entire image


sensor_aligner:
  zed_roi_params: {y_s: 250, y_e: 1650, x_s: 0, x_e: 1080} # jai search region in zed
  size: 640 #what size to resize image to
  affine_method: keypoints # keypoints will use keypoints, loftr will use loftr
  ransac: 20
  sx: 0.6284895833333334 #0.6315104 #0.60546875
  sy: 0.6652678396871945 # 0.6133919843597263
  roix: 970 #970 #930 #937
  roiy: 1255
  debug:
    preprocess: false
    keypoints: false
    kde: false
    homography: false

frame_loader:
  mode: sync_mkv # sync_mkv, async,  sync_svo


filters:
  distance:
    threshold: 1
  duplicates:
    iou_threshold: 0.6
  size:
    size_threshold: 2500
  height:
    bias: -100
    y_crop: 200
  hue: true # flag for using hue filter
  depth: true # flag for using dynamic depth filter

clusters:
  min_single_fruit_distance: 150

