# config.yaml
exp_file: /home/fruitspec-lab/FruitSpec/Code/fsCounter/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr_RGB.py # Lab 1
#exp_file: /home/fruitspec-lab-3/FruitSpec/Code/Matan/fsCounter_1/vision/detector/yolo_x/exps/fruitspec/fs_yolox_tiny_lr_RGB.py  # tomatoes lab3

ckpt_file: /home/fruitspec-lab/FruitSpec/weights/Run_6_Dec_2022_1Class_aug_tasqV2/best_ckpt.pth # RGB tasq v2 Lab 1
#ckpt_file: /home/fruitspec-lab-3/FruitSpec/weights/Run_6_Dec_2022_1Class_aug_tasqV2/best_ckpt.pth # RGB tasq v2 lab3

device: cuda

input_size: [1024, 1024]

dim_method: pix_size_median # with what method to get the dimensions, reg - old method, ellipsoid - ellipsoid fitting,
                    #pix_size_median - by pixel size median, pix_size_mean - by pixel size mean, reg_kde - old method with kde filtering
margin: 0.2 # the lower the margin the more pixels we take from the center

detector:
  confidence: 0.7
  nms: 0.6
  num_of_classes: 1
  fp16: true
  fuse: false
  trt: false

classes:
  full: 0
  partial: 1

tracker:
  minimal_max_distance: 10
  major: 1.2 #3
  minor: 0.8 #2.5
  max_losses: 3  # 10
  score_weights: [0.5, 1, 0.5, 1, 0] # [0.25, 1.0, 0.25, 0.0] # [0.25, 1.0, 0.25, 1]
  match_type:  inter #center
  det_area: 0.7
  translation_size: 640

translation:
  translation_size: 480
  mode: match # match: use template matching, keypoints: use keypoints detection
  dets_only: true # true: perfrom on detections only, false: on entire image


filters:
  distance:
    threshold: 10
  duplicates:
    iou_threshold: 0.6
  size:
    size_threshold: 2500
  height:
    bias: -100
    y_crop: 200
  hue: true # flag for using hue filter
  depth: true # flag for using dynamic depth filter

clusters:
  max_single_fruit_dist: 150
  range_diff_threshold: 0.05
  max_losses: 5

