movie_path:  /home/fruitspec-lab-3/FruitSpec/Sandbox/Counter/FSI_Stretch/wetransfer_clahe-first-exp_2023-03-09_1309/clahe_975_exp8K/
output_folder:  /home/fruitspec-lab-3/FruitSpec/Sandbox/Counter/FSI_Stretch/test2
#movie_path:

frame_size:  [1920, 1080] # [2048, 1536]
rotate: 1 # 0: no rotate, 1: COUNTERCLOCKWISE, 2: CLOCKWISE
depth_minimum: 0.1 # 1 counter
depth_maximum: 2.5 # 8 counter

debug:
  is_debug: true  # master switch
  tracker_windows: true
  tracker_results: true
  det_results: false
  raw_frame: false
  depth: false
  tracker: None
  clusters: false

