movie_path: /home/yotam/FruitSpec/Sandbox/Syngenta/pre_ZED_90.svo
output_folder: /home/yotam/FruitSpec/Sandbox/Syngenta/tomatoes/pre_ZED_90_1Class_aug_5
#movie_path:

frame_size:  [1920, 1080] # [2048, 1536]
rotate: true

debug:
  is_debug: true  # master switch
  tracker_windows: true
  tracker_results: true
  det_results: false
  raw_frame: false
  depth: false

