movie_path: /home/fruitspec-lab/Downloads/0.8m1stm/ZED_1.svo
output_folder:  /home/fruitspec-lab/Downloads/0.8m1stm/output
output_folder_track: $(output_folder)/tracking
output_folder_annotate: $(output_folder)/annotation

frame_size:  [1920, 1080] # [2048, 1536]
rotate: 2 # 0: no rotate, 1: COUNTERCLOCKWISE, 2: CLOCKWISE
depth_minimum: 0
depth_maximum: 8

debug:
  is_debug: true  # master switch
  tracker_windows: false
  tracker_results: false
  det_results: false
  raw_frame: false
  depth: false
  tracker: None
  clusters: true
  hue_histogram: false
  annotate: false

