movie_path: /media/yotam/Extreme SSD/syngenta trail/tomatoes/YATED61R/HD1080_SN39018199_11-11-44.svo
output_folder: /home/yotam/FruitSpec/Sandbox/Syngenta/YATED61R_3
frame_size: [1920, 1080]
rotate: true

