movie_path: /home/fruitspec-lab/Downloads/0.8m1sts/ZED_1.svo
output_folder:  /home/fruitspec-lab/Downloads/0.8m1sts/output
output_folder_track:  /home/fruitspec-lab/Downloads/0.8m1sts/output/tracking
output_folder_annotate:  /home/fruitspec-lab/Downloads/0.8m1sts/output/annotation

frame_size: [1920, 1080] # [1920, 1080] # [2048, 1536]
rotate: 2 # 0: no rotate, 1: COUNTERCLOCKWISE, 2: CLOCKWISE
depth_minimum: 0.1 # 1 counter
depth_maximum: 2.5 # 8 counter

debug:
  is_debug: true  # master switch
  tracker_windows: false
  tracker_results: false
  det_results: false
  raw_frame: true
  depth: false
  tracker: None
  clusters: false
  hue_histogram: false
  annotate: true

