movie_path: /home/yotam/FruitSpec/Data/tasq/batch3/A/Result_FSI.mkv
output_folder: /home/yotam/FruitSpec/Data/tasq/batch3/A
output_folder_track: /home/yotam/FruitSpec/Data/tasq/batch3/A/tracking
output_folder_annotate: /home/yotam/FruitSpec/Data/tasq/batch3/A/annotation

frame_size: [2048, 1536] # [1920, 1080] # [2048, 1536]
rotate: 2 # 0: no rotate, 1: COUNTERCLOCKWISE, 2: CLOCKWISE
depth_minimum: 0.1 # 1 counter
depth_maximum: 2.5 # 8 counter

debug:
  is_debug: true  # master switch
  tracker_windows: false
  tracker_results: false
  det_results: false
  raw_frame: false
  depth: false
  tracker: None
  clusters: false
  hue_histogram: false
  annotate: true

