fruit_type: tomato
scan_date: '230123'
main_path_com: /media/yotam/Extreme SSD/syngenta trail
analysis_path: ${main_path_com}/${fruit_type}/analysis/${scan_date}
output_path: ${main_path_com}/${fruit_type}/analysis/${scan_date}
video_path: ${main_path_com}/${fruit_type}/${scan_date}