fruit_type: tomato
scan_date: '230123'
analysis_path: /home/fruitspec-lab/Downloads/${fruit_type}/analysis/${scan_date}
output_path: /home/fruitspec-lab/Downloads/${fruit_type}/analysis/${scan_date}
video_path: /home/fruitspec-lab/Downloads/${fruit_type}/${scan_date}