pre_path: '/media/yotam/Extreme SSD/syngenta trail/tomato/analysis/230123/pre'
post_path: '/media/yotam/Extreme SSD/syngenta trail/tomato/analysis/230123/post'
output_path: '/media/yotam/Extreme SSD/syngenta trail/tomato/analysis/230123'